name: hao_chatgpt
description: An unofficial ChatGPT application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.3+7

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  yaml: ^3.1.1
  json_annotation: ^4.7.0
  retrofit: '>=3.0.0 <4.0.0'
  logger: ^1.1.0
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  riverpod: ^2.1.3
  loading_animation_widget: ^1.2.0+4
  shared_preferences: ^2.0.15
  go_router: ^6.0.0
  webview_flutter: ^4.0.1
  webview_flutter_android: ^3.1.1
  webview_flutter_wkwebview: ^3.0.1
  url_launcher: ^6.1.7
  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.12
  path_provider: ^2.0.11
  path: ^1.8.2
  android_intent_plus: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  flutter_lints: ^2.0.1
  drift_dev: ^2.4.1

flutter:
#  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - openai.yaml
    - pubspec.yaml
